### ISSUE TITLE
documentation should provide idiot-proof instructions how to try HEAD

### ISSUE THREAD

**Issue by ge0ffrey** [awestruct/awestruct.github.io#47]
So it's quick&easy to answer "can you reproduce that bug with head".

Personally, I 'd make a separate page.

Links that might help to figure out what the instructions are:

```
http://awestruct.org/getting_started/
In a nutshell use git gems in your Gemfile: http://bundler.io/v1.3/git.html
gem 'awestruct', :github => 'awestruct'
```

**Comment by LightGuard** [comment]
Mind writing that up and submitting it as a PR?

**Comment by ge0ffrey** [comment]
Normally I send in PR's instead of issues for Awestruct, but I fear I didn't send one for this issue because I never got around to figuring it out. I presume gem versions has some sort of -SNAPSHOT suffix like in maven?

**Comment by LightGuard** [comment]
Not typically, no. Some will do alpha, beta, rc. Many use Git refs in the
Gemfile.

On Wednesday, February 10, 2016, Geoffrey De Smet <notifications@github.com>
wrote:

> Normally I send in PR's instead of issues for Awestruct, but I fear I
> didn't send one for this issue because I never got around to figuring it
> out. I presume gem versions has some sort of -SNAPSHOT suffix like in maven?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct.org/issues/47#issuecomment-182251023>
> .
>


-- 
Sent from Gmail Mobile

**Comment by mojavelinux** [comment]
In the Ruby world, the repository itself is the snapshot version (so the version doesn't actually matter). Assuming you add the following to the Gemfile:

```
gem 'awestruct', github: 'awestruct'
```

or, more formally:

```
gem 'awestruct', github: 'awestruct/awestruct', ref: 'master'
```

Then when you run `bundle` (or `bundle update awestruct`), Bundler will clone the repository and put it on the load path. If you're inside a project with a Gemfile that declares this dependency, you can run `awestruct` and it will execute the gem bin script automatically (using its binstub dispatch mechanism).

Another way to test it is to simply install the gem into your current Ruby environment. Go to the Awestruct clone and type:

```
rake install
```

That's the same as:

```
rake build
gem install pkg/awestruct-*.gem
```

Then, you can use `awestruct` from any directory. (Keep in mind that if you're using RVM, you must install the gem into the same Ruby version and gemset that you'll be using).

**Comment by zbynek** [comment]
Ideally we can avoid unreleased commits, which makes this unnecessary.
